language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
scripts:
  - RAILS_ENV=test bundle exec rake test
notifications:
  email:
    recipients:
      - grauwoelfchen@gmail.com
    on_success: change
    on_failure: always
