language: ruby
addons:
  postgresql: "9.3"
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
before_script:
  - psql -U postgres -c "CREATE DATABASE travis_ci_test;"
  - mv test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace
scripts:
  - RAILS_ENV=test bundle exec rake test
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - grauwoelfchen@gmail.com
  webhooks:
    on_success: change
    on_failure: always
    urls:
      - secure: CmLUsWVJMXSiYynScQBlpSjXOfMQif0hlfZFmgld8+5vs1nbP6RPi39vDsVzxD21REDN1FIL48AEaYP1HeRFnHmf+qQKebcRhsKoxphhSv71rhFspsxWTlI3FTFdtywx2UICq7fHOAcbzx4q2OiUyays3cTLsVojBCZiPAqpScw=
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
